Revert "Show why ffprobe fails"
This reverts commit 0c7643e44f9bd4b98e791ed0554231fbc74b8f81
as it results in
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)